// Product database and keyword matching engine for Gaming Problem Solver
// 15 categories, 45 products, 20 example problems

import { Product } from '@/types';

export const products: Product[] = [

  // --- SEATING / BACK & NECK PAIN -------------------------------------------
  {
    id: 'secretlab-titan-evo',
    name: 'Secretlab TITAN Evo 2022',
    category: 'seating',
    price: '$399',
    rating: 4.8,
    reviewCount: 12847,
    pros: [
      'Patented 4-way adjustable lumbar system',
      'Cold-cure foam maintains shape for years',
      '4D armrests + multi-tilt mechanism',
      'Available in 3 sizes (Small / Regular / XL)',
    ],
    cons: [
      'Higher price than budget chairs',
      '30-45 min assembly required',
      'Foam takes 2-3 weeks to fully break in',
    ],
    whySolves: "The TITAN Evo's built-in adjustable lumbar directly targets the lower-back pain caused by gaming slouch. The multi-tilt mechanism lets you recline to a posture-neutral angle, taking pressure off your spine.",
    viewUrl: 'https://secretlab.co',
    badge: "Editor's Pick",
    gradientFrom: '#1a1040',
    gradientTo: '#0d0820',
  },
  {
    id: 'autonomous-ergchair-pro',
    name: 'Autonomous ErgoChair Pro',
    category: 'seating',
    price: '$499',
    rating: 4.5,
    reviewCount: 8234,
    pros: [
      'Fully adjustable lumbar + headrest',
      'Breathable mesh back stays cool',
      'Weight-sensitive recline tension',
      'Eco-friendly TPE armrests',
    ],
    cons: [
      'Mesh can feel firm the first week',
      'Premium price point',
      'Limited colour options',
    ],
    whySolves: "ErgoChair Pro's mesh back keeps airflow moving so you don't shift from heat, and the adaptive lumbar support keeps your spine aligned without you thinking about it.",
    viewUrl: 'https://autonomous.ai',
    badge: 'Best for Posture',
    gradientFrom: '#0f2027',
    gradientTo: '#203a43',
  },
  {
    id: 'noblechairs-hero',
    name: 'noblechairs HERO Series',
    category: 'seating',
    price: '$349',
    rating: 4.6,
    reviewCount: 5621,
    pros: [
      'Integrated lumbar + neck pillow included',
      'Rocking function relieves static pressure',
      'Premium PU leather or velour options',
      '4D armrests',
    ],
    cons: [
      'Leather retains heat over long sessions',
      'Heavy at 28 kg -- hard to reposition',
      'No mesh version',
    ],
    whySolves: "The integrated pillows prevent spinal misalignment as sessions go on, while the rocking function means you're never locked into one rigid position that builds into neck and back pain.",
    viewUrl: 'https://noblechairs.com',
    gradientFrom: '#2d1b69',
    gradientTo: '#1a0533',
  },

  // --- BUDGET HEADSET (UNDER $50) -------------------------------------------
  {
    id: 'hyperx-cloud-stinger',
    name: 'HyperX Cloud Stinger',
    category: 'budget-headset',
    price: '$39.99',
    rating: 4.4,
    reviewCount: 34521,
    pros: [
      '50mm directional drivers',
      'Memory foam ear cushions',
      'Rotating ear cups for easy travel',
      'In-line volume slider',
    ],
    cons: [
      'No virtual surround sound',
      'Short 1.3m cable',
      'Plastic frame feels light',
    ],
    whySolves: "HyperX's audio tuning delivers clear directional sound at under $40 -- you'll hear footsteps and positional cues in-game without spending more than a game costs.",
    viewUrl: 'https://hyperx.com',
    badge: 'Best Under $40',
    gradientFrom: '#1a0505',
    gradientTo: '#2a0808',
  },
  {
    id: 'steelseries-arctis-1',
    name: 'SteelSeries Arctis 1',
    category: 'budget-headset',
    price: '$49.99',
    rating: 4.3,
    reviewCount: 18903,
    pros: [
      'Retractable ClearCast mic -- no boom arm needed',
      'Works on PC, PS, Xbox, Switch, mobile',
      'Steel-reinforced headband',
      'Lightweight at 160g',
    ],
    cons: [
      'Stereo only -- no surround',
      'No inline volume control',
      'Ear cups warm after 2+ hours',
    ],
    whySolves: "The Arctis 1 brings SteelSeries' professional ClearCast mic to a sub-$50 price -- your teammates will hear you clearly without you spending $100+.",
    viewUrl: 'https://steelseries.com',
    badge: 'Best Mic Under $50',
    gradientFrom: '#0a0f1a',
    gradientTo: '#141e30',
  },
  {
    id: 'corsair-hs35',
    name: 'Corsair HS35 Stereo',
    category: 'budget-headset',
    price: '$34.99',
    rating: 4.2,
    reviewCount: 22417,
    pros: [
      'Plush memory foam ear cups',
      'Durable aluminium yoke',
      'Works across all major platforms',
      'Detachable noise-cancelling mic',
    ],
    cons: [
      'Average mic clarity',
      '3.5mm only -- no USB',
      'Basic sound signature',
    ],
    whySolves: "At under $35 the HS35 is Corsair's budget workhorse -- comfortable for 6+ hour sessions and durable enough to last, solving the problem of cheap headsets that fall apart after three months.",
    viewUrl: 'https://corsair.com',
    badge: 'Most Comfortable',
    gradientFrom: '#0a1428',
    gradientTo: '#1a2a4a',
  },

  // --- MICROPHONE -----------------------------------------------------------
  {
    id: 'blue-yeti',
    name: 'Blue Yeti USB Microphone',
    category: 'microphone',
    price: '$129.99',
    rating: 4.7,
    reviewCount: 87234,
    pros: [
      'Four polar patterns (cardioid, stereo, omni, bidirectional)',
      'Plug-and-play USB -- no audio interface needed',
      'Built-in headphone amp for zero-latency monitoring',
      'Industry-standard clarity',
    ],
    cons: [
      'Large and heavy -- benefits from a boom arm',
      'Sensitive to background noise in cardioid mode',
      'USB-A only -- no USB-C version',
    ],
    whySolves: "The Yeti's cardioid mode captures your voice with studio clarity while rejecting keyboard, fan, and room noise -- your Discord and in-game comms will sound immediately more professional.",
    viewUrl: 'https://bluemic.com',
    badge: 'Most Popular',
    gradientFrom: '#0d0d1a',
    gradientTo: '#1a1a2e',
  },
  {
    id: 'hyperx-quadcast-s',
    name: 'HyperX QuadCast S',
    category: 'microphone',
    price: '$159.99',
    rating: 4.6,
    reviewCount: 12043,
    pros: [
      'Anti-vibration shock mount built in',
      'Built-in pop filter',
      'Tap-to-mute with LED status indicator',
      'RGB via HyperX NGENUITY',
    ],
    cons: [
      'Premium price point',
      'RGB requires software install',
      'USB-C only',
    ],
    whySolves: "The QuadCast S ships with the two accessories -- shock mount and pop filter -- that fix 80% of bad mic problems on their own. Zero extra equipment, immediately professional sound.",
    viewUrl: 'https://hyperx.com',
    badge: 'Best All-in-One',
    gradientFrom: '#2a0808',
    gradientTo: '#1a0404',
  },
  {
    id: 'elgato-wave3',
    name: 'Elgato Wave:3',
    category: 'microphone',
    price: '$149.99',
    rating: 4.5,
    reviewCount: 9876,
    pros: [
      'Clipguard prevents distortion when you get loud',
      'Wave Link software -- mix game/voice/music separately',
      'Capacitive mute button (no accidental presses)',
      'Best in class for streaming setups',
    ],
    cons: [
      'Cardioid only -- one pickup pattern',
      'Wave Link required for advanced features',
      'Slightly pricier than the Yeti',
    ],
    whySolves: "Clipguard automatically prevents your mic from clipping when you spike -- no more distorted yells mid-game. Wave Link lets you control exactly how your voice sounds to teammates.",
    viewUrl: 'https://elgato.com',
    badge: 'Best for Streamers',
    gradientFrom: '#0a0a14',
    gradientTo: '#14142a',
  },

  // --- FPS MOUSE ------------------------------------------------------------
  {
    id: 'logitech-gpx-superlight2',
    name: 'Logitech G Pro X Superlight 2',
    category: 'fps-mouse',
    price: '$159.99',
    rating: 4.9,
    reviewCount: 45231,
    pros: [
      'Ultra-light at 60g -- reduces fatigue dramatically',
      'HERO 2 sensor -- zero acceleration or smoothing',
      'LIGHTSPEED wireless -- sub-1ms latency',
      '95-hour battery life',
    ],
    cons: [
      'Expensive',
      'No RGB -- pure performance focus',
      'Right-handed only',
    ],
    whySolves: "Used by the majority of top CS2, Valorant, and Apex players. At 60g with a flawless sensor, the Superlight 2 eliminates the tracking inconsistencies that make your aim feel unreliable.",
    viewUrl: 'https://logitech.com',
    badge: 'Pro Player Choice',
    gradientFrom: '#1a1a08',
    gradientTo: '#0e0e04',
  },
  {
    id: 'razer-deathadder-v3',
    name: 'Razer DeathAdder V3',
    category: 'fps-mouse',
    price: '$79.99',
    rating: 4.7,
    reviewCount: 28904,
    pros: [
      'Iconic ergonomic shape -- fits palm and claw grip',
      'Focus Pro 30K optical sensor',
      'Ultra-light at 59g',
      'Optical switches -- zero debounce delay',
    ],
    cons: [
      'Right-handed only',
      'Wired version only at this price',
      'Basic side button placement',
    ],
    whySolves: "The ergonomic shape keeps your hand in a natural position for hours -- no cramping. Optical switches fire the instant you click, which means no missed shots from contact bounce.",
    viewUrl: 'https://razer.com',
    badge: 'Best Ergonomic',
    gradientFrom: '#1a0a14',
    gradientTo: '#0a0508',
  },
  {
    id: 'pulsar-xlite-v2-mini',
    name: 'Pulsar Xlite V2 Mini',
    category: 'fps-mouse',
    price: '$69.99',
    rating: 4.6,
    reviewCount: 11234,
    pros: [
      'Featherweight at 55g',
      'PAW3370 sensor -- competition-grade accuracy',
      'Available in Regular and Mini size',
      'No RGB drag -- pure performance',
    ],
    cons: [
      'Honeycomb shell collects dust over time',
      'Smaller brand = less retail support',
      'Shorter battery life vs G Pro X',
    ],
    whySolves: "At 55g with a competition-grade sensor, the Xlite V2 Mini removes every gram of unnecessary weight so your wrist works less and your tracking stays precise through 6-hour sessions.",
    viewUrl: 'https://pulsargg.com',
    badge: 'Lightest Pick',
    gradientFrom: '#081420',
    gradientTo: '#04090e',
  },

  // --- SWEATY HANDS ---------------------------------------------------------
  {
    id: 'razer-viper-v3-pro',
    name: 'Razer Viper V3 Pro',
    category: 'sweaty-hands',
    price: '$159.99',
    rating: 4.8,
    reviewCount: 19823,
    pros: [
      'Textured side grips engineered for moisture',
      'Ambidextrous -- works for both hands',
      'Focus Pro 35K sensor',
      'High-traction PTFE feet',
    ],
    cons: [
      'No side buttons on the right side',
      'High price point',
      'Requires Razer Synapse for full config',
    ],
    whySolves: "The Viper V3 Pro's rubberized side grips and moisture-resistant coating are specifically designed to maintain control when your hands sweat -- built for high-intensity gameplay.",
    viewUrl: 'https://razer.com',
    badge: 'Best Anti-Sweat',
    gradientFrom: '#080e1a',
    gradientTo: '#0e1628',
  },
  {
    id: 'gaming-gloves-grip',
    name: 'Grip Clean Gaming Gloves',
    category: 'sweaty-hands',
    price: '$24.99',
    rating: 4.1,
    reviewCount: 8432,
    pros: [
      'Fingerless -- full mouse control preserved',
      'Anti-sweat lycra absorbs moisture at the source',
      'Machine washable',
      'Works with any mouse or controller',
    ],
    cons: [
      'Adjustment period required -- feels odd at first',
      'Sizing varies by brand',
      "Some players never adjust to the feel",
    ],
    whySolves: "Gaming gloves absorb sweat at the palm before it ever reaches your mouse, while keeping all fingers free for clicking and scrolling. Cheapest, most universal fix for sweaty hands.",
    viewUrl: 'https://amazon.com',
    gradientFrom: '#0a1e0a',
    gradientTo: '#061006',
  },
  {
    id: 'steelseries-prime-plus',
    name: 'SteelSeries Prime+',
    category: 'sweaty-hands',
    price: '$59.99',
    rating: 4.5,
    reviewCount: 14209,
    pros: [
      'Magnetic optical switches -- no sticking when wet',
      'Grip tape pre-installed in box',
      'TrueMove Pro sensor',
      'Anti-fingerprint matte coating',
    ],
    cons: [
      'Right-handed only',
      'SteelSeries GG software for full config',
      'Fewer thumb buttons than competitors',
    ],
    whySolves: "Magnetic optical switches don't stick or misfire when wet -- solving the double-click issue sweaty fingers cause. Comes with grip tape already installed, nothing extra to buy.",
    viewUrl: 'https://steelseries.com',
    badge: 'Best Value',
    gradientFrom: '#100a1e',
    gradientTo: '#080512',
  },

  // --- KEYBOARD -------------------------------------------------------------
  {
    id: 'wooting-60he',
    name: 'Wooting 60HE',
    category: 'keyboard',
    price: '$174.99',
    rating: 4.9,
    reviewCount: 7823,
    pros: [
      'Rapid Trigger -- key resets at any point in the press',
      'Analog input (variable actuation depth)',
      'Fully programmable via Wootility',
      'Hot-swappable Lekker switches',
    ],
    cons: [
      '60% layout -- no function row or numpad',
      'Learning curve with Wootility software',
      'High price for a 60%',
    ],
    whySolves: "Rapid Trigger resets the key the instant you release it rather than waiting for a fixed reset point. This gives you faster strafing and counter-strafing than is physically possible with any standard keyboard.",
    viewUrl: 'https://wooting.io',
    badge: 'Best Competitive',
    gradientFrom: '#1a0a28',
    gradientTo: '#0e0516',
  },
  {
    id: 'logitech-gpx-tkl',
    name: 'Logitech G Pro X TKL Wireless',
    category: 'keyboard',
    price: '$129.99',
    rating: 4.6,
    reviewCount: 21034,
    pros: [
      'LIGHTSPEED wireless -- zero input lag',
      'Tenkeyless -- more room for wide mouse movements',
      'Hot-swappable switches (linear/tactile/clicky)',
      'Per-key RGB',
    ],
    cons: [
      '~40 hours battery with RGB on',
      'Higher price for a TKL',
      'US layout only in some markets',
    ],
    whySolves: "Removing the numpad lets you centre your keyboard and pull your mouse in, giving you the wider arcs for low-sensitivity FPS play that a full-size keyboard physically prevents.",
    viewUrl: 'https://logitech.com',
    badge: 'Pro Standard',
    gradientFrom: '#080d1a',
    gradientTo: '#04060e',
  },
  {
    id: 'steelseries-apex-pro-mini',
    name: 'SteelSeries Apex Pro Mini',
    category: 'keyboard',
    price: '$179.99',
    rating: 4.7,
    reviewCount: 9421,
    pros: [
      'OmniPoint 2.0 -- adjustable actuation per key',
      'OLED Smart Display for quick profiles',
      'Aircraft-grade aluminium frame',
      'PrismSync per-key RGB',
    ],
    cons: [
      'Most expensive keyboard on this list',
      'No function row in 60% form',
      'Loud actuation',
    ],
    whySolves: "OmniPoint 2.0 lets you set each key's actuation point independently -- WASD ultra-sensitive for movement while spacebar stays normal. Precision tuned to your exact play style.",
    viewUrl: 'https://steelseries.com',
    badge: 'Most Customizable',
    gradientFrom: '#081a08',
    gradientTo: '#040e04',
  },

  // --- MONITOR --------------------------------------------------------------
  {
    id: 'lg-27gp850',
    name: 'LG UltraGear 27GP850-B',
    category: 'monitor',
    price: '$349.99',
    rating: 4.7,
    reviewCount: 18234,
    pros: [
      '180Hz -- virtually eliminates motion blur',
      '1ms GtG response time',
      'Nano IPS -- great colours + fast response',
      'G-Sync Compatible + FreeSync Premium',
    ],
    cons: [
      '1440p demands a mid-to-high GPU',
      'Stand limited to tilt and height',
      'Some units have backlight bleed at edges',
    ],
    whySolves: "At 180Hz with 1ms response, the LG 27GP850 eliminates the screen tearing and motion blur that makes you miss shots or react a frame too late. Plug it in and tearing is gone.",
    viewUrl: 'https://lg.com',
    badge: 'Best 1440p Value',
    gradientFrom: '#080a1a',
    gradientTo: '#04050e',
  },
  {
    id: 'asus-rog-swift-360',
    name: 'ASUS ROG Swift 360Hz PG259QN',
    category: 'monitor',
    price: '$699.99',
    rating: 4.5,
    reviewCount: 6234,
    pros: [
      '360Hz -- the absolute fastest panels available',
      'G-Sync Ultimate certified',
      '1ms MPRT response time',
      'ELMB Sync backlight strobing',
    ],
    cons: [
      'Very expensive',
      '1080p only at this refresh rate',
      'Needs RTX GPU to reach 360fps',
    ],
    whySolves: "360Hz essentially eliminates perceived motion blur -- you see the enemy fractions of a second before a 144Hz player does. Measurable in pro scrimmages and ranked matches alike.",
    viewUrl: 'https://asus.com',
    badge: 'Fastest Available',
    gradientFrom: '#1a0808',
    gradientTo: '#0e0404',
  },
  {
    id: 'samsung-odyssey-g5',
    name: 'Samsung Odyssey G5 32"',
    category: 'monitor',
    price: '$299.99',
    rating: 4.4,
    reviewCount: 22891,
    pros: [
      '165Hz refresh rate',
      '1ms MPRT response time',
      '1000R curved panel -- immersive feel',
      'AMD FreeSync Premium Pro',
    ],
    cons: [
      'VA panel -- lower viewing angles than IPS',
      'Curve may not suit all setups',
      'No G-Sync compatibility',
    ],
    whySolves: "The Odyssey G5 brings 165Hz and 1ms response to an accessible price point, eliminating tearing with FreeSync. The curve also reduces eye strain during marathon sessions.",
    viewUrl: 'https://samsung.com',
    badge: 'Best Value',
    gradientFrom: '#080e1a',
    gradientTo: '#04070e',
  },

  // --- STREAMING ------------------------------------------------------------
  {
    id: 'elgato-hd60x',
    name: 'Elgato HD60 X Capture Card',
    category: 'streaming',
    price: '$149.99',
    rating: 4.7,
    reviewCount: 14302,
    pros: [
      '4K30 or 1080p60 HDR passthrough',
      'Plug-and-play with OBS, Streamlabs, XSplit',
      'Ultra-low latency preview (VRR)',
      'Works with PS5, Xbox, and PC simultaneously',
    ],
    cons: [
      '4K capture requires the 4K60 upgrade ($199)',
      'Standalone PC still required for encoding',
      'USB 3.0 port mandatory',
    ],
    whySolves: "The HD60 X captures your console or PC gameplay in real time and sends it to your streaming PC without any quality loss -- the fastest way to get from zero to live on Twitch.",
    viewUrl: 'https://elgato.com',
    badge: 'Best for Console',
    gradientFrom: '#021414',
    gradientTo: '#010a0a',
  },
  {
    id: 'elgato-stream-deck',
    name: 'Elgato Stream Deck MK.2',
    category: 'streaming',
    price: '$149.99',
    rating: 4.8,
    reviewCount: 29481,
    pros: [
      '15 customizable LCD keys -- one press for any action',
      'Switch scenes, mute mic, launch alerts in real time',
      'Deep integrations: OBS, Twitch, YouTube, Discord',
      'Drag-and-drop setup via Stream Deck app',
    ],
    cons: [
      'Requires Stream Deck software',
      'Learning curve to set up profiles',
      'Single USB-C connection -- no wireless',
    ],
    whySolves: "Managing OBS while playing costs you focus and mistakes. The Stream Deck moves every streaming action to a dedicated button panel so your game attention never breaks.",
    viewUrl: 'https://elgato.com',
    badge: 'Streamer Essential',
    gradientFrom: '#0d0214',
    gradientTo: '#06010a',
  },
  {
    id: 'logitech-streamcam',
    name: 'Logitech StreamCam 1080p',
    category: 'streaming',
    price: '$169.99',
    rating: 4.5,
    reviewCount: 18750,
    pros: [
      "1080p60 with AI-powered face tracking",
      'USB-C -- plug into any modern PC or Mac',
      'Landscape and portrait mode (for TikTok/Shorts)',
      'Logi Capture software for filters and settings',
    ],
    cons: [
      'No 4K -- limited to 1080p60',
      'Face tracking can feel artificial',
      'Fixed focal length lens',
    ],
    whySolves: "A high-quality facecam is what separates hobbyist from professional streams. The StreamCam's 1080p60 and AI face tracking keep you sharp and centred even when you move around.",
    viewUrl: 'https://logitech.com',
    badge: 'Best Webcam',
    gradientFrom: '#080a1a',
    gradientTo: '#04050e',
  },

  // --- WRIST PAIN -----------------------------------------------------------
  {
    id: 'razer-wrist-rest-pro',
    name: 'Razer Pro Wrist Rest',
    category: 'wrist-pain',
    price: '$39.99',
    rating: 4.3,
    reviewCount: 9814,
    pros: [
      'Memory foam molds to wrist shape',
      'Non-slip rubber base',
      'Full-length desk pad version available',
      'Neutral wrist angle reduces RSI risk',
    ],
    cons: [
      'Memory foam compresses over 1-2 years',
      'Only useful if paired with proper chair height',
      'Not machine washable',
    ],
    whySolves: "A wrist rest keeps your wrist in a neutral, flat position rather than extended upward, which is the primary cause of wrist pain and repetitive strain during long gaming sessions.",
    viewUrl: 'https://razer.com',
    badge: 'Most Comfortable',
    gradientFrom: '#0a0418',
    gradientTo: '#05020c',
  },
  {
    id: 'logitech-mx-master-3s',
    name: 'Logitech MX Master 3S',
    category: 'wrist-pain',
    price: '$99.99',
    rating: 4.8,
    reviewCount: 31027,
    pros: [
      'Sculpted ergonomic shape reduces pronation',
      'Quiet clicks -- 90% less click noise',
      'MagSpeed scroll wheel for fast scrolling',
      'USB-C charging -- never use batteries',
    ],
    cons: [
      'Not a gaming sensor -- 8K DPI max',
      'Right-handed only',
      'Larger size may not suit small hands',
    ],
    whySolves: "The MX Master 3S's sculpted shape keeps your wrist in its most natural resting position, reducing the forearm rotation that causes strain during long sessions.",
    viewUrl: 'https://logitech.com',
    badge: 'Most Ergonomic',
    gradientFrom: '#081a12',
    gradientTo: '#040e09',
  },
  {
    id: 'corsair-mm500-deskpad',
    name: 'Corsair MM500 Extended Deskpad',
    category: 'wrist-pain',
    price: '$44.99',
    rating: 4.6,
    reviewCount: 12443,
    pros: [
      'Micro-textured surface prevents wrist abrasion',
      'Anti-slip rubber base stays put',
      'Covers full keyboard + mouse area',
      'Waterproof surface -- easy to clean',
    ],
    cons: [
      'No cushioning -- surface only, not raised',
      'Edges may peel after 2-3 years',
      'Only comes in black',
    ],
    whySolves: "A smooth deskpad eliminates the hard edge contact and friction that causes wrist abrasion and pain, while giving your arm a consistent glide surface that reduces repetitive micro-stress.",
    viewUrl: 'https://corsair.com',
    gradientFrom: '#040a14',
    gradientTo: '#02050a',
  },

  // --- LIGHTING / BATTLE STATION RGB ----------------------------------------
  {
    id: 'elgato-key-light-air',
    name: 'Elgato Key Light Air',
    category: 'lighting',
    price: '$129.99',
    rating: 4.7,
    reviewCount: 21509,
    pros: [
      '2500 lumens -- daylight-quality illumination',
      'Adjustable colour temp (2900K-7000K)',
      'Wi-Fi controlled via app or Stream Deck',
      'Slim panel -- minimal desk footprint',
    ],
    cons: [
      'Pricey for a desk light',
      'No RGB -- whites only',
      'Needs power outlet',
    ],
    whySolves: "A key light eliminates the flat, shadowy look that webcam footage gets under ceiling lighting, giving your stream a polished, broadcast-quality appearance that builds viewer retention.",
    viewUrl: 'https://elgato.com',
    badge: 'Best Key Light',
    gradientFrom: '#1a1200',
    gradientTo: '#0e0900',
  },
  {
    id: 'govee-rgbic-strips',
    name: 'Govee RGBIC LED Strip Lights',
    category: 'lighting',
    price: '$29.99',
    rating: 4.4,
    reviewCount: 48210,
    pros: [
      '16M colours + RGBIC simultaneous multicolour',
      'Music sync mode reacts to game audio',
      'Govee Home app or voice control',
      'Adhesive backing -- installs in 10 min',
    ],
    cons: [
      'Adhesive weakens in high-heat environments',
      'App can be glitchy on older phones',
      'Colour accuracy varies at lower brightness',
    ],
    whySolves: "Govee strips add bias lighting behind your monitor and desk, which reduces eye strain by bringing ambient light closer to screen brightness -- and makes your setup look incredible on stream.",
    viewUrl: 'https://govee.com',
    badge: 'Best Value RGB',
    gradientFrom: '#14001a',
    gradientTo: '#0a000e',
  },
  {
    id: 'benq-screenbar-halo',
    name: 'BenQ ScreenBar Halo',
    category: 'lighting',
    price: '$199.99',
    rating: 4.8,
    reviewCount: 9832,
    pros: [
      'Front light for work + bias backlight in one',
      'Auto-dimming based on ambient light sensor',
      'No screen glare -- downward-only beam',
      'USB-C powered directly from your monitor',
    ],
    cons: [
      'Most expensive desk light on this list',
      'Requires a monitor with USB-C power delivery',
      "Can't be used as a key light for streaming",
    ],
    whySolves: "The ScreenBar Halo eliminates eye strain by lighting your desk without any light hitting the screen, while providing the bias backlight glow behind the monitor that makes dark rooms comfortable.",
    viewUrl: 'https://benq.com',
    badge: 'Premium Pick',
    gradientFrom: '#0a0814',
    gradientTo: '#05040a',
  },

  // --- CONTROLLER -----------------------------------------------------------
  {
    id: 'xbox-elite-series-2',
    name: 'Xbox Elite Series 2',
    category: 'controller',
    price: '$179.99',
    rating: 4.6,
    reviewCount: 38210,
    pros: [
      'Adjustable hair trigger locks -- faster shooting',
      'Four removable paddles for extra bindings',
      'Rubberized grip wrap',
      'Up to 40-hour built-in rechargeable battery',
    ],
    cons: [
      'Expensive -- nearly 3x a standard controller',
      'Known bumper failure in some early units',
      'Heavy at 345g',
    ],
    whySolves: "Paddles give you four extra buttons reachable without lifting your thumbs off the sticks -- a genuine advantage in any game where moving and performing actions simultaneously matters.",
    viewUrl: 'https://xbox.com',
    badge: "Editor's Pick",
    gradientFrom: '#001a08',
    gradientTo: '#000e04',
  },
  {
    id: 'powera-enhanced-wireless',
    name: 'PowerA Enhanced Wireless Controller',
    category: 'controller',
    price: '$49.99',
    rating: 4.2,
    reviewCount: 24503,
    pros: [
      'Two mappable advanced gaming buttons',
      '30-hour AA battery life',
      'Officially Xbox/PC licensed',
      'Comfortable grips at half the Elite price',
    ],
    cons: [
      'No rechargeable battery included',
      'Buttons feel slightly less premium',
      'Limited firmware support',
    ],
    whySolves: "Officially licensed and Xbox/PC compatible out of the box, the PowerA Enhanced gets you working immediately with two extra mappable buttons -- without the $130 price jump to the Elite.",
    viewUrl: 'https://powera.com',
    badge: 'Best Budget',
    gradientFrom: '#001408',
    gradientTo: '#000a04',
  },
  {
    id: 'razer-wolverine-v2-chroma',
    name: 'Razer Wolverine V2 Chroma',
    category: 'controller',
    price: '$199.99',
    rating: 4.5,
    reviewCount: 11240,
    pros: [
      '6 remappable multi-function buttons',
      'Hair trigger mode on both triggers',
      'Mecha-tactile action buttons (faster actuation)',
      'Chroma RGB + Razer Nexus app',
    ],
    cons: [
      'Wired only -- no wireless version',
      'Heavy at 380g',
      'Razer Nexus app required for remapping',
    ],
    whySolves: "The Wolverine's mecha-tactile face buttons actuate faster than standard dome switches, and 6 remappable buttons mean every ability or action is always one finger away without thumb movement.",
    viewUrl: 'https://razer.com',
    gradientFrom: '#1a0208',
    gradientTo: '#0e0104',
  },

  // --- NETWORKING -----------------------------------------------------------
  {
    id: 'tp-link-archer-axe5400',
    name: 'TP-Link Archer AXE5400',
    category: 'networking',
    price: '$149.99',
    rating: 4.5,
    reviewCount: 13892,
    pros: [
      'Wi-Fi 6E -- dedicated 6GHz band avoids congestion',
      '5400 Mbps combined throughput',
      'Prioritize gaming devices via QoS',
      'OFDMA reduces latency in multi-device homes',
    ],
    cons: [
      'Wi-Fi 6E requires compatible device to benefit',
      'Large router footprint',
      'Setup can be complex for beginners',
    ],
    whySolves: "Wi-Fi 6E's dedicated 6GHz band is congestion-free -- no neighbours competing for bandwidth. Combined with QoS, your console or PC gets priority over every other device in the house.",
    viewUrl: 'https://tp-link.com',
    badge: 'Best Wi-Fi 6E',
    gradientFrom: '#00081a',
    gradientTo: '#00040e',
  },
  {
    id: 'plugable-usb-ethernet',
    name: 'TP-Link USB to 2.5G Ethernet Adapter',
    category: 'networking',
    price: '$22.99',
    rating: 4.7,
    reviewCount: 31047,
    pros: [
      '2.5 Gbps -- faster than standard 1G ports',
      'USB-A 3.0 and USB-C versions available',
      'No drivers needed on Windows 10/11 or macOS',
      'Dramatically lowers ping vs Wi-Fi',
    ],
    cons: [
      'Requires a 2.5G router/switch to max out',
      'Cable run to router required',
      'USB-C to USB-A adapter may be needed for laptops',
    ],
    whySolves: "A wired ethernet connection eliminates packet loss, jitter, and interference that causes the lag spikes you feel in online matches. A $23 adapter and one cable run fixes it permanently.",
    viewUrl: 'https://tp-link.com',
    badge: 'Instant Fix',
    gradientFrom: '#000a14',
    gradientTo: '#00050a',
  },
  {
    id: 'netgear-nighthawk-xr1000',
    name: 'Netgear Nighthawk XR1000 Pro',
    category: 'networking',
    price: '$299.99',
    rating: 4.4,
    reviewCount: 8903,
    pros: [
      'DumaOS 3.0 -- gaming-specific traffic shaping',
      'Geo-filter: choose which servers you connect to',
      'Real-time ping monitor and network map',
      'Wi-Fi 6 AX5400',
    ],
    cons: [
      'Expensive for a router',
      'DumaOS has a steep learning curve',
      'Overkill for casual gaming',
    ],
    whySolves: "The XR1000's DumaOS lets you filter matchmaking to nearby servers only, cutting your ping to the lowest possible for your region -- and the QoS is specifically tuned for gaming traffic.",
    viewUrl: 'https://netgear.com',
    badge: 'Most Powerful',
    gradientFrom: '#00041a',
    gradientTo: '#00020e',
  },

  // --- DESK ORGANIZATION ----------------------------------------------------
  {
    id: 'ergotron-lx-arm',
    name: 'Ergotron LX Monitor Arm',
    category: 'desk',
    price: '$159.99',
    rating: 4.8,
    reviewCount: 47821,
    pros: [
      'Supports up to 34" / 11.3kg monitors',
      'Full articulation -- tilt, pan, rotate, height',
      'Frees up your entire desk surface',
      'Premium build -- used in offices worldwide',
    ],
    cons: [
      'Pricier than clamp-style budget arms',
      'Requires desk at least 25mm thick',
      'Cable management not included',
    ],
    whySolves: "Mounting your monitor on an arm clears 100% of the stand footprint off your desk, giving you back valuable space for a larger mousepad, notebook, or second screen -- instantly.",
    viewUrl: 'https://ergotron.com',
    badge: 'Best Monitor Arm',
    gradientFrom: '#0a0808',
    gradientTo: '#050404',
  },
  {
    id: 'corsair-mm350-pro',
    name: 'Corsair MM350 Pro Extended',
    category: 'desk',
    price: '$49.99',
    rating: 4.6,
    reviewCount: 19203,
    pros: [
      '900x400mm -- covers keyboard + mouse area',
      'Micro-weave fabric prevents fraying edges',
      'Stitched border edge',
      'Anti-slip rubber base',
    ],
    cons: [
      'Takes 48h to fully flatten after unboxing',
      'One size -- no XL option',
      'No RGB version available',
    ],
    whySolves: "A full-coverage desk mat unifies your keyboard and mouse surface, eliminates the hard-desk friction that slows your mouse, and prevents cables snagging -- solving multiple desk problems at once.",
    viewUrl: 'https://corsair.com',
    badge: 'Best Desk Mat',
    gradientFrom: '#040a10',
    gradientTo: '#020508',
  },
  {
    id: 'ugreen-cable-management',
    name: 'UGREEN Cable Management Box',
    category: 'desk',
    price: '$24.99',
    rating: 4.5,
    reviewCount: 28430,
    pros: [
      'Hides power strips and excess cables completely',
      'Fire-retardant material',
      'Cable routing slots on both ends',
      'Comes in two sizes (M/L)',
    ],
    cons: [
      "Doesn't fit very large power strips",
      'White colour may not match dark setups',
      'No ventilation -- check device heat requirements',
    ],
    whySolves: "Cable chaos is a focus and hygiene issue, not just aesthetic. A cable box hides your power brick and excess runs in one step, making your desk surface clean and distraction-free.",
    viewUrl: 'https://ugreen.com',
    gradientFrom: '#040810',
    gradientTo: '#020408',
  },

  // --- HEADSET COMFORT / EAR FATIGUE ----------------------------------------
  {
    id: 'brainwavz-velour-pads',
    name: 'Brainwavz Angled Velour Ear Pads',
    category: 'headset-comfort',
    price: '$25.99',
    rating: 4.5,
    reviewCount: 18720,
    pros: [
      'Angled design reduces ear canal pressure',
      'Velour breathes -- stays cool for hours',
      'Compatible with most over-ear headsets',
      'Immediate upgrade for under $30',
    ],
    cons: [
      'Slight bass reduction vs leatherette pads',
      'Compatibility must be verified per headset',
      'No fitting tool included',
    ],
    whySolves: "Velour pads eliminate the heat and pressure that build up when leather or pleather pads trap air against your ear. Swapping pads is the fastest and cheapest fix for ear fatigue.",
    viewUrl: 'https://brainwavzaudio.com',
    badge: 'Instant Upgrade',
    gradientFrom: '#14041a',
    gradientTo: '#0a020e',
  },
  {
    id: 'steelseries-arctis-nova-1',
    name: 'SteelSeries Arctis Nova 1',
    category: 'headset-comfort',
    price: '$49.99',
    rating: 4.5,
    reviewCount: 14832,
    pros: [
      'Ultra-lightweight at 197g -- barely noticeable',
      'Infinity Comfort band -- no pressure points on head',
      'Broad platform support (PC, PS, Xbox, Switch)',
      'Clear 40mm speaker drivers',
    ],
    cons: [
      'No wireless -- 3.5mm only',
      'No surround sound processing',
      'Basic mic compared to higher-tier SteelSeries',
    ],
    whySolves: "At 197g with SteelSeries' pressure-distributing Infinity Comfort band, the Nova 1 is engineered to be nearly invisible on your head -- the lightweight build is the direct fix for ear and head pressure.",
    viewUrl: 'https://steelseries.com',
    badge: 'Ultra-Lightweight',
    gradientFrom: '#0e0418',
    gradientTo: '#07020c',
  },
  {
    id: 'logitech-g435',
    name: 'Logitech G435 Wireless',
    category: 'headset-comfort',
    price: '$79.99',
    rating: 4.4,
    reviewCount: 21047,
    pros: [
      'Ultra-light at 165g -- lightest on this list',
      'Soft ear cushions -- no heat buildup',
      'Dual wireless (Bluetooth + USB dongle)',
      '18-hour battery life',
    ],
    cons: [
      'No microphone boom arm -- built-in only',
      'Mic quality is acceptable but not great',
      'No EQ customization without Logitech G HUB',
    ],
    whySolves: "At 165g, the G435 is one of the lightest gaming headsets ever made -- the reduced clamping force and soft cushions mean you forget you're wearing it, eliminating the ear pain caused by heavier headsets.",
    viewUrl: 'https://logitech.com',
    badge: 'Lightest Wireless',
    gradientFrom: '#050a18',
    gradientTo: '#02050c',
  },

  // --- BUDGET MOUSE (UNDER $40) ---------------------------------------------
  {
    id: 'logitech-g305',
    name: 'Logitech G305 Wireless',
    category: 'budget-mouse',
    price: '$39.99',
    rating: 4.7,
    reviewCount: 58320,
    pros: [
      'HERO sensor -- same accuracy as flagship mice',
      'LIGHTSPEED wireless -- 1ms report rate',
      '250-hour battery on single AA battery',
      'Compact symmetric shape fits any grip',
    ],
    cons: [
      'AA battery adds slight weight',
      'Only 5 buttons -- no extra side buttons',
      'No RGB',
    ],
    whySolves: "The G305 uses the same HERO sensor as mice three times the price, in a wireless form that plays with zero lag. Best bang-for-buck gaming mouse under $40 -- not even close.",
    viewUrl: 'https://logitech.com',
    badge: 'Best Under $40',
    gradientFrom: '#080a1a',
    gradientTo: '#04050e',
  },
  {
    id: 'razer-deathadder-essential',
    name: 'Razer DeathAdder Essential',
    category: 'budget-mouse',
    price: '$29.99',
    rating: 4.4,
    reviewCount: 43219,
    pros: [
      '6400 DPI optical sensor -- accurate for the price',
      "Iconic ergonomic DeathAdder shape",
      'Durable Razer mechanical switches (10M clicks)',
      'Plug-and-play -- no software required',
    ],
    cons: [
      'Wired only',
      'No side texture -- can feel slippery',
      'Right-handed only',
    ],
    whySolves: "The DeathAdder Essential brings Razer's famous ergonomic shape and reliable mechanical switches to under $30 -- a genuine step up from a bundled or no-name mouse without spending real money.",
    viewUrl: 'https://razer.com',
    gradientFrom: '#0e0406',
    gradientTo: '#070203',
  },
  {
    id: 'glorious-model-o-minus',
    name: 'Glorious Model O Minus',
    category: 'budget-mouse',
    price: '$49.99',
    rating: 4.5,
    reviewCount: 22841,
    pros: [
      'Featherweight honeycomb shell at 58g',
      'BAMF 19K sensor',
      'Flexible ultraweave cable (feels wireless)',
      'Available in regular and matte finishes',
    ],
    cons: [
      'Honeycomb collects dust over time',
      'Less mainstream support than Logitech/Razer',
      'Can feel fragile due to low weight',
    ],
    whySolves: "At 58g with a competition-grade sensor and a cable that flexes like wireless, the Model O Minus gives you the feel of a $150 mouse at a $50 price -- the honeycomb shell removes every gram that isn't essential.",
    viewUrl: 'https://gloriousgaming.com',
    badge: 'Lightest Budget',
    gradientFrom: '#040810',
    gradientTo: '#020408',
  },

];

// --- Keyword map -----------------------------------------------------------
// Each category maps to trigger words. More matches = higher score.
const categoryKeywords: Record<string, string[]> = {
  seating:            ['back', 'neck', 'posture', 'spine', 'lumbar', 'chair', 'sit', 'shoulder', 'hurt', 'pain', 'ache', 'sore', 'ergonomic', 'uncomfortable chair'],
  'budget-headset':   ['budget', 'cheap', 'affordable', 'under $50', '$50', 'inexpensive', 'headset', 'headphones', 'low cost'],
  microphone:         ['microphone', 'mic', 'sounds bad', 'sound bad', 'hear me', "can't hear", 'voice', 'discord', 'stream', 'recording', 'muffled', 'quiet mic', 'bad audio', 'audio quality'],
  'fps-mouse':        ['fps', 'aim', 'accuracy', 'shooter', 'headshot', 'valorant', 'cs2', 'csgo', 'competitive', 'precise', 'inconsistent aim', 'miss shots', 'tracking'],
  'sweaty-hands':     ['sweaty', 'sweat', 'slippery', 'grip', 'wet hands', 'sweaty hands', 'palm', 'slides', 'slip'],
  keyboard:           ['keyboard', 'keys', 'mechanical', 'actuation', 'tenkeyless', 'tkl', 'switches', 'keypress', 'strafing'],
  monitor:            ['monitor', 'screen', 'display', 'hz', 'hertz', 'refresh', 'resolution', 'blur', 'tearing', 'stutters', 'screen tearing', 'lag on screen'],
  streaming:          ['stream', 'streaming', 'twitch', 'youtube', 'obs', 'capture', 'broadcast', 'webcam', 'facecam', 'live'],
  'wrist-pain':       ['wrist', 'wrist pain', 'wrist hurts', 'carpal', 'rsi', 'repetitive strain'],
  lighting:           ['lighting', 'rgb', 'key light', 'ring light', 'bias lighting', 'battle station', 'setup looks', 'room light', 'led'],
  controller:         ['controller', 'gamepad', 'joystick', 'console', 'xbox', 'playstation', 'ps5', 'ps4', 'pad'],
  networking:         ['lag', 'ping', 'disconnect', 'internet', 'connection', 'wifi', 'latency', 'packet loss', 'lags', 'online', 'disconnects'],
  desk:               ['desk', 'cable', 'cables', 'organize', 'organization', 'desk mat', 'mousepad', 'monitor arm', 'clutter', 'space', 'tidy'],
  'headset-comfort':  ['ear pain', 'ears hurt', 'headset hurts', 'ears ache', 'ear fatigue', 'heavy headset', 'uncomfortable headset', 'ears after'],
  'budget-mouse':     ['budget mouse', 'cheap mouse', 'affordable mouse', 'mouse under', '$40 mouse', '$30 mouse', 'mouse cheap', 'gaming mouse under'],
};

// Score the problem text against every category and return the top 3 products
export function matchProducts(problemText: string): Product[] {
  const lower = problemText.toLowerCase();

  const scores: Record<string, number> = {};

  for (const [category, keywords] of Object.entries(categoryKeywords)) {
    scores[category] = keywords.reduce((acc, kw) => acc + (lower.includes(kw) ? 1 : 0), 0);
  }

  // Prefer budget-mouse over fps-mouse when explicit budget language is present
  const hasBudgetMouseSignal = ['budget mouse', 'cheap mouse', 'mouse under', '$40', '$30'].some(kw => lower.includes(kw));
  if (hasBudgetMouseSignal) {
    scores['fps-mouse'] = Math.max(0, scores['fps-mouse'] - 3);
  }

  // Prefer budget-headset only when both a budget keyword AND audio keyword are present
  const hasBudgetAudioSignal =
    ['budget', 'cheap', 'affordable', 'under $50', '$50'].some(kw => lower.includes(kw)) &&
    ['headset', 'headphones', 'audio'].some(kw => lower.includes(kw));
  if (!hasBudgetAudioSignal) {
    scores['budget-headset'] = Math.max(0, scores['budget-headset'] - 2);
  }

  const bestCategory = Object.entries(scores)
    .sort(([, a], [, b]) => b - a)
    .find(([, score]) => score > 0)?.[0];

  if (!bestCategory) {
    // Fallback: mixed showcase of top-rated products from different categories
    return [
      products.find(p => p.id === 'secretlab-titan-evo')!,
      products.find(p => p.id === 'logitech-gpx-superlight2')!,
      products.find(p => p.id === 'hyperx-quadcast-s')!,
    ];
  }

  return products.filter(p => p.category === bestCategory).slice(0, 3);
}

// --- 20 curated example problems shown on the Examples page ----------------
export const exampleProblems: Array<{
  problem: string;
  category: string;
  icon: string;
}> = [
  { problem: 'My back hurts when gaming',                              category: 'Ergonomics',   icon: '🪑' },
  { problem: 'I need a good headset under $50',                       category: 'Budget Audio',  icon: '🎧' },
  { problem: 'My hands get sweaty when gaming',                       category: 'Comfort',       icon: '🖱️' },
  { problem: 'My microphone sounds bad on Discord',                   category: 'Audio',         icon: '🎙️' },
  { problem: 'I need a precise gaming mouse for FPS games',           category: 'FPS',           icon: '🎯' },
  { problem: 'My neck hurts after long gaming sessions',              category: 'Ergonomics',    icon: '😣' },
  { problem: 'I want a fast mechanical keyboard for competitive play', category: 'Input',        icon: '⌨️' },
  { problem: 'My monitor stutters and has screen tearing',            category: 'Display',       icon: '🖥️' },
  { problem: 'I want to start streaming on Twitch',                   category: 'Streaming',     icon: '📡' },
  { problem: 'My wrist hurts after long gaming sessions',             category: 'Ergonomics',    icon: '💪' },
  { problem: 'I need better RGB lighting for my battle station',      category: 'Lighting',      icon: '💡' },
  { problem: 'I need a controller for PC gaming',                     category: 'Controller',    icon: '🎮' },
  { problem: 'My game lags and disconnects during online matches',    category: 'Networking',    icon: '📶' },
  { problem: 'I need to organize my desk and cable setup',            category: 'Desk',          icon: '🗂️' },
  { problem: 'My headset hurts my ears after 2 hours',               category: 'Comfort',       icon: '👂' },
  { problem: 'I need a gaming mouse under $40',                       category: 'Budget',        icon: '💰' },
  { problem: 'My gaming chair is uncomfortable and hurts my spine',  category: 'Ergonomics',    icon: '🪑' },
  { problem: 'My team cannot hear me clearly in game chat',          category: 'Audio',         icon: '🔊' },
  { problem: 'My aim feels inconsistent and I keep missing shots',   category: 'FPS',           icon: '🎯' },
  { problem: 'I need a webcam to stream my face on Twitch',          category: 'Streaming',     icon: '📷' },
];

// Category display metadata for the Examples page filter tabs
export const problemCategories = [
  'All', 'Ergonomics', 'Audio', 'Budget', 'Budget Audio',
  'FPS', 'Display', 'Streaming', 'Lighting', 'Controller',
  'Networking', 'Desk', 'Comfort', 'Input',
];
